site_name: Hongliang's Wiki
repo_name: qiuhong-1202/CS-Docs
repo_url: https://github.com/qiuhong-1202/CS-Document
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.tracking 
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - content.code.copy
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
    logo: boot/snowman
  palette:
    primary: white
  favicon: images/snowman-circle.png
  font:
    code: JetBrains Mono
    text: Noto Sans SC

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: false
      # preview: false
      # inline_syntax: ['dollar']
      # block_syntax: ['dollar']

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

extra_javascript:
  # - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css
  - stylesheets/extra.css